spring.application.name=JobSwipe

# Google OAuth2 settings
app.security.oauth2.google.client-id=${GOOGLE_CLIENT_ID:481782536231-hqteg554tiqniln7cjmfhirduih8tg47.apps.googleusercontent.com}
app.security.oauth2.google.client-secret=${GOOGLE_CLIENT_SECRET:}
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://accounts.google.com
