spring.application.name=JobSwipe

spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

google.oauth.client-id=${GOOGLE_OAUTH_CLIENT_ID:481782536231-hqteg554tiqniln7cjmfhirduih8tg47.apps.googleusercontent.com}
