spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.data-source-properties.preferQueryMode=simple

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

google.oauth.client-id=${GOOGLE_OAUTH_CLIENT_ID}
google.oauth.client-secret=${GOOGLE_OAUTH_CLIENT_SECRET}

app.jwt.issuer=${APP_JWT_ISSUER}
app.jwt.access-token-expiration-seconds=${APP_JWT_EXPIRATION_SECONDS}
app.jwt.secret=${APP_JWT_SECRET}

app.domain=${APP_DOMAIN}
